-- 코드를 작성해주세요
SELECT IDS.3ST_ID AS ID
FROM (SELECT A.ID AS 3ST_ID,B.ID AS 2ST_ID,B.PARENT_ID AS 1ST_ID
FROM ECOLI_DATA A, ECOLI_DATA B
WHERE A.PARENT_ID = B.ID AND B.PARENT_ID IS NOT NULL) AS IDS LEFT JOIN ECOLI_DATA ON IDS.1ST_ID = ECOLI_DATA.ID
WHERE ECOLI_DATA.PARENT_ID IS NULL
ORDER BY ID ASC



