-- 코드를 입력하세요
SELECT I.REST_ID,
       I.REST_NAME,
       I.FOOD_TYPE,
       I.FAVORITES,
       I.ADDRESS,
       S.SCORE
FROM REST_INFO I
JOIN (
    SELECT R.REST_ID,
           ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW R
    JOIN REST_INFO I2 ON R.REST_ID = I2.REST_ID
    WHERE I2.ADDRESS LIKE '서울%'
    GROUP BY R.REST_ID
) S ON I.REST_ID = S.REST_ID
ORDER BY S.SCORE DESC, I.FAVORITES DESC;